### PR TITLE
2.2.0

### PR DESCRIPTION
**Pull request by NateIorgMX**
# What's New

- `hushConfigureGitlab` now validates input, and will badger users until a valid value is entered.
- Refactored general flow with drivers, allowing for much easier extension.
- Validation on API responses, with reporting, to allow users to more easily troubleshoot configuration errors (or server outages).
- Gitlab searches are now asynchronous.
- Suggested suppressions no longer contain invalid notes (carried over from existing suppressions), if an issue can be found.

### CODE REVIEW

**Comment by NateIorgMX** [comment]
> Is this going to be compatible with @SandhyaBhatia Java 17 upgrade?

@RyanJones08 Yep! After testing her PR locally, I threw in some preliminary fixes based on some deprecation warnings I saw. This should be totally compatible, and we're planning on bundling both into `2.2.0`.

**Comment by mattnichols** [comment]
Code looks good! Let's squash these commits.

**Comment by mattnichols** [comment]
Do any of these changes warrant a README update?

**Comment by NateIorgMX** [comment]
> Do any of these changes warrant a README update?

@mattnichols I don't think so. There are a lot of behind-the-scenes changes but nothing that should warrant a readme change.

**Pull request merged**
